name: Upload Changed Files to AnythingLLM (with folder structure)

on:
  push:
    branches:
      - main

jobs:
  upload-documents:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Sync files
        id: changed-files
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD); do
            filename=$(basename "$file")
            workplace=$(basename $(dirname "$file"))
            api_url="https://anythingllm.gto-stat.ru/api/v1"
            json=$(curl -sS -X POST $api_url/document/upload/lighthouse \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              -F "file=@$file" \
              --fail-with-body)
              echo "$json" | jq '.'
            
              curl -X POST $api_url/workspace/lighthouse/update-embeddings \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" 
               -d "{\"deletes\": [\"$filename\"]}"
               
              curl -X POST $api_url/workspace/lighthouse/update-embeddings \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              -d "{\"adds\": [\"$filename\"]}"
          done
