name: Upload Changed Files to AnythingLLM (with folder structure)

on:
  push:
    branches:
      - main

jobs:
  upload-documents:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Sync files
        id: changed-files
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD); do
            filename=$(basename "$file")
            workplace=$(basename $(dirname "$file"))
            api_url="https://anythingllm.gto-stat.ru/api/v1"
            echo "информация о workspace $workplace"
           
            json=$(curl -s $api_url/workspace/$workplace \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              --fail-with-body)

            delete_file=$(echo "$json" | jq --arg filename "$filename" '.workspace[0].documents[] | select(.metadata | fromjson.title == $filename).filename')
              if [ -n "$delete_file" ]; then
              echo "удаляем существующий файл"
               curl -s -X POST $api_url/system/remove-documents \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              -d "{\"names\": [\"$delete_file\"]}"> /dev/null 2>&1 
              fi
             echo "Загружаем файл  $file"
            json=$(curl -s -X POST $api_url/document/upload/$workplace \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              -F "file=@$file" \
              --fail-with-body)
              location=$(echo "$json" | jq -r '.documents[0].location')

              delete_emb=$(echo "$json" | jq --arg filename "$filename" '.workspace.documents[] | select(.metadata | fromjson.title == $filename).filename')
              if [ -n "$delete_emb" ]; then
                echo "Удаляю embedding $delete_emb"
                curl -s -X POST $api_url/workspace/$workplace/update-embeddings \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
                -d "{\"deletes\": [\"$delete_emb\"]}" > /dev/null 2>&1
              fi

              echo "Новый embedding $delete_emb"
              curl -s -X POST $api_url/workspace/$workplace/update-embeddings \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              -d "{\"adds\": [\"$location\"]}"> /dev/null 2>&1 
          done
