name: Upload Changed Files to AnythingLLM (with folder structure)

on:
  push:
    branches:
      - main

jobs:
  upload-documents:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: |
          for file in $(git show --name-only --pretty=format: HEAD | tail -n +2); do
            curl -X POST https://anythingllm.gto-stat.ru/api/v1/document/upload/$(dirname "$file") \
              -H "Authorization: Bearer SPZ09E6-DND41HB-GAW3MJC-BT3HYZN" \
              -F "file=@$file" \
              --fail-with-body
          done
